CONTRIBUTING.md
LICENSE.md
chrony/.README.j2
chrony/Dockerfile

Collection of minor textual changes to the add-on.
n/a

Collection of textual changes

---

chrony/rootfs/etc/cont-init.d/10-requirements.sh
chrony/rootfs/etc/cont-init.d/20-configuration.sh
chrony/rootfs/etc/services.d/chronyd/run

Simplified the bash scripts in the add-on.
Tried to minimize the logic, reducing needed calls, while still maintaining the same functionality.
n/a

Simplifies add-on code logic

---

.gitattributes

Update gitattributes to resolve LF issues
None

:art: Changing git attributes file

---

.gitlab-ci.yml
chrony/Dockerfile
chrony/build.json

:hammer: Updating image to 3.0.1

---

.gitlab-ci.yml
README.md
chrony/Dockerfile
chrony/build.json

:books: Readme Update

---

.gitlab-ci.yml
README.md
chrony/Dockerfile
chrony/build.json

:books: Readme Linting

---

README.md

:books: readme updates

---

chrony/Dockerfile
chrony/build.json

:hammer: Update base image

---

.gitlab-ci.yml

Missed the gitlab config...., updating
None

:card_index: Update gitlab config

---

chrony/config.json

Adds a description to the port.
Took the liberty to format the document and remove obsoletes as well.
n/a

✨Adds port descriptions

---

.gitlab-ci.yml
chrony/Dockerfile
chrony/build.json

:arrow_up: Upgrade addon base to 3.1.1

---

.gitlab-ci.yml
chrony/Dockerfile
chrony/build.json

⬆ Update base to 3.1.2

---

README.md

📚 Update Readme to Prod Ready

---

LICENSE.md
README.md
chrony/.README.j2
chrony/DOCS.md

📚 Update year in documentation

---

README.md
chrony/DOCS.md

Updates docs for GH actions and branch rename

📚 Documentation updates

---

chrony/Dockerfile
chrony/build.json

https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2

Upgrade add-on base image to 9.1.2

---

chrony/Dockerfile
chrony/build.json

⬆ Update base image to v9.1.5

---

chrony/Dockerfile
chrony/build.json

⬆️ Upgrades add-on base image to v9.1.7

⬆️ Upgrades add-on base image to v9.1.7

---

chrony/Dockerfile
chrony/build.json

Upgrades add-on base image to v9.2.0

Upgrades add-on base image to v9.2.0

---

chrony/Dockerfile
chrony/build.json

Upgrades add-on base image to v9.2.2

⬆️ Upgrades add-on base image to v9.2.2

---

chrony/Dockerfile
chrony/build.json

⬆ Update base image to v10.0.0
⬆ Update chrony to v4.1-r0
https://chrony.tuxfamily.org/news.html

⬆ Update base image to v10.0.0 and chrony to v4.1-r0

---

chrony/Dockerfile
chrony/build.json

Upgrades add-on base image to v10.0.1

⬆️Upgrades add-on base image to v10.0.1

---

chrony/Dockerfile
chrony/build.json

Update add-on base image to v10.0.2

⬆️ Update add-on base image to v10.0.2

---

chrony/Dockerfile
chrony/build.json

⬆️ Update base image to 11.0.0

⬆️ Update base image to 11.0.0

---

LICENSE.md
README.md
chrony/.README.j2
chrony/DOCS.md

📚 Update year 🎉

---

chrony/Dockerfile
chrony/build.json

Upgrades add-on base image to 11.0.1

⬆️ Upgrades add-on base image to 11.0.1

---

chrony/DOCS.md

Making it easier to find the add-on

:books: Add My buttons to documentation

---

chrony/Dockerfile
chrony/build.yaml
chrony/rootfs/etc/cont-init.d/chrony.sh
chrony/rootfs/etc/services.d/chronyd/finish
chrony/rootfs/etc/services.d/chronyd/run

Upgrades add-on base image to 12.0.0

⬆️ Upgrades add-on base image to 12.0.0

---

chrony/DOCS.md

Less documentation, single-click button doing both. Just a little easier.

:books: Use new My Home Assistant link format

---

LICENSE.md
README.md
chrony/.README.j2
chrony/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

chrony/Dockerfile
chrony/build.yaml

bump Chrony to 4.3-r0
bump base image to 13.0.0

:arrow_up: Upgrades add-on base image to 13.1.1

---

README.md
chrony/build.yaml
chrony/config.yaml

Drop support for armhf & i386

---

LICENSE.md
README.md
chrony/.README.j2
chrony/DOCS.md

:fireworks: Updates maintenance/license year to 2024

---

LICENSE.md
README.md
chrony/.README.j2
chrony/DOCS.md

:fireworks: Updates maintenance/license year to 2025
